version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: task_tracker_db
      MYSQL_USER: task_tracker_user
      MYSQL_PASSWORD: task_tracker_password
    ports:
      - "3306:3306"
    volumes:
      - "./initdb.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
       db:
        condition: service_healthy
